spring:
  application:
    name: user-micro-service
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: postgres
    hikari:
      auto-commit: true
      schema: app
server:
  port: 8081